apiVersion: v1
kind: Service
metadata:
  name: comfyui-{{ .Values.name }}-svc
  labels:
    app: comfyui-{{ .Values.name }}
spec:
  type: NodePort
  selector:
    app: comfyui-{{ .Values.name }}
  ports:
    - protocol: TCP
      port: 8188         # 내부 Pod 포트
      targetPort: 8188   # Pod에서 사용하는 포트
      {{- if .Values.nodePort }}
      nodePort: {{ .Values.nodePort }}    # 외부에서 접근할 포트 (30000~32767 사이에서 설정 가능)
      {{- end }}