apiVersion: v1
kind: PersistentVolume
metadata:
  name: cui-output-{{ .Values.name }}-pv
spec:
  capacity:
    storage: {{ .Values.storageSize | default "20G" | quote }}
  accessModes:
    - ReadWriteMany
  claimRef:
    namespace: {{ .Values.namespace | default "default" | quote }}
    name: cui-output-{{ .Values.name }}-pvc
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: {{ .Values.nfs.server }}
    path: {{ .Values.nfs.path }}/{{ .Values.name }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cui-output-{{ .Values.name }}-pvc
  namespace: {{ .Values.namespace | default "default" | quote }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storageSize | default "20G" | quote }}